#!/bin/sh

REPO=ratakor-repo
PKG=${*:-$(ls packages)}
ROOTCMD="${ROOTCMD:-$(command -v doas || command -v sudo)}"

for pkg in $PKG; do
	rm -f "x86_64/$pkg"*
	(cd "packages/$pkg" &&
		rm -f ./*.pkg.tar.zst ./*.pkg.tar.zst.sig
		makepkg -scf --sign)
done

cp -f packages/*/*.pkg.tar.zst x86_64/
cp -f packages/*/*.pkg.tar.zst.sig x86_64/
rm -f x86_64/$REPO.db* x86_64/$REPO.files*
repo-add -s -v x86_64/$REPO.db.tar.gz x86_64/*.pkg.tar.zst
unlink x86_64/$REPO.db
unlink x86_64/$REPO.files
unlink x86_64/$REPO.db.sig
unlink x86_64/$REPO.files.sig
mv x86_64/$REPO.db.tar.gz x86_64/$REPO.db
mv x86_64/$REPO.files.tar.gz x86_64/$REPO.files
mv x86_64/$REPO.db.tar.gz.sig x86_64/$REPO.db.sig
mv x86_64/$REPO.files.tar.gz.sig x86_64/$REPO.files.sig
sed -i "s/Last.*/Last updated: $(date -R)/" README.md

if pacman -Qqdt 1>/dev/null; then
	printf "Type your password to remove orphaned packages\n"
	# shellcheck disable=SC2046
	"$ROOTCMD" pacman -Rns $(pacman -Qqdt)
fi

gitui # review changes

printf "Do you want to push ? (y/N) "
read -r ANSWER
case $ANSWER in
	y*|Y*)
		git add .
		git commit -m "update"
		git push
		#rm -rf ../ratakor-repo-github/x86_64/
		#cp -rf ./* ../ratakor-repo-github/
		#(cd ../ratakor-repo-github || exit 1
		#git add .
		#git commit -m "update"
		#git push) ;;
esac
